//
// Created by zzk on 2021/10/19.
//

#ifndef CMAKE_CPP_CUDA_CMAKE_D_SHARED_LIBRARY_INCLUDE_SHARED_HELLO_H_
#define CMAKE_CPP_CUDA_CMAKE_D_SHARED_LIBRARY_INCLUDE_SHARED_HELLO_H_

class Hello {
 public:
  void SayHello();
};

#endif //CMAKE_CPP_CUDA_CMAKE_D_SHARED_LIBRARY_INCLUDE_SHARED_HELLO_H_
